// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGicPEgI043aLppwQCUMXvAkchjrvvRpI',
    appId: '1:188121960005:android:09b6ce990f2258fc719d2c',
    messagingSenderId: '188121960005',
    projectId: 'ma-01-carrentapp',
    storageBucket: 'ma-01-carrentapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLnrVAnJTl0m7sUB--Twx8-U_UsNnwh_g',
    appId: '1:188121960005:ios:59cc93f797a656ed719d2c',
    messagingSenderId: '188121960005',
    projectId: 'ma-01-carrentapp',
    storageBucket: 'ma-01-carrentapp.firebasestorage.app',
    iosBundleId: 'com.msalmannaeem.carrentapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaVW3Uw8V-P-S3llTii5A0rs9X96GZatI',
    appId: '1:188121960005:web:7dcac3bc55581172719d2c',
    messagingSenderId: '188121960005',
    projectId: 'ma-01-carrentapp',
    authDomain: 'ma-01-carrentapp.firebaseapp.com',
    storageBucket: 'ma-01-carrentapp.firebasestorage.app',
    measurementId: 'G-6Z6JQDWM8Q',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLnrVAnJTl0m7sUB--Twx8-U_UsNnwh_g',
    appId: '1:188121960005:ios:59cc93f797a656ed719d2c',
    messagingSenderId: '188121960005',
    projectId: 'ma-01-carrentapp',
    storageBucket: 'ma-01-carrentapp.firebasestorage.app',
    iosBundleId: 'com.msalmannaeem.carrentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaVW3Uw8V-P-S3llTii5A0rs9X96GZatI',
    appId: '1:188121960005:web:a629c73e6baf1889719d2c',
    messagingSenderId: '188121960005',
    projectId: 'ma-01-carrentapp',
    authDomain: 'ma-01-carrentapp.firebaseapp.com',
    storageBucket: 'ma-01-carrentapp.firebasestorage.app',
    measurementId: 'G-Z7KSNCPWC7',
  );

}